export const REQUEST_BOOKS_LIST = 'REQUEST_BOOKS_LIST';
export const RECEIVE_BOOKS_LIST = 'RECEIVE_BOOKS_LIST';
export const REQUEST_BOOK_DETAILS = 'REQUEST_BOOK_DETAILS';
export const RECEIVE_BOOK_DETAILS = 'RECEIVE_BOOK_DETAILS';
export const STORE_EXPANDED_BOOK = 'STORE_EXPANDED_BOOK';
export const LOG_ERROR_BOOK = 'LOG_ERROR_BOOK';
export const LOG_ERROR_BOOKDETAILS = 'LOG_ERROR_BOOKDETAILS';